considered_venues = [
    "ieee trans. pattern anal. mach. intell",
    "sigir",
    "www",
    "ieee transactions on information theory",
    "kdd",
    "expert syst. appl",
    "inf. sci",
    "sigmod conference",
    "journal of machine learning research",
    "ieee trans. knowl. data eng",
    "ieee computer",
    "commun. acm",
    "ieee journal on selected areas in communications",
    "cikm",
    "ieee transactions on neural networks",
    "pattern recognition",
    "icde",
    "acm multimedia",
    "ijcai",
    "pattern recognition letters",
    "vldb",
    "machine learning",
    "neural computation",
    "acm comput. surv",
    "icdm",
    "icml",
    "ieee trans. computers",
    "ieee transactions on systems, man, and cybernetics, part b",
    "bioinformatics",
    "decision support systems",
    "aaai",
    "cvpr (2)",
    "artif. intell",
    "siam j. comput",
    "sac",
    "ieee transactions on multimedia",
    "cvpr (1)",
    "information systems research",
    "j. artif. intell. res. (jair)",
    "j. acm",
    "neurocomputing",
    "pvldb",
    "ieee intelligent systems",
    "information & management",
    "acm trans. inf. syst",
    "j. of management information systems",
    "vldb j",
    "pods",
    "siam j. scientific computing",
    "computer communication review",
    "acm trans. database syst",
    "data knowl. eng",
    "ieee transactions on systems, man, and cybernetics, part a",
    "future generation comp. syst",
    "inf. process. manage",
    "sigmod record",
    "computers & mathematics with applications",
    "inf. process. lett",
    "j. comput. syst. sci",
    "neural networks",
    "wsdm",
    "sigkdd explorations",
    "computational statistics & data analysis",
    "knowl.-based syst",
    "ieee transactions on systems, man, and cybernetics, part c",
    "data min. knowl. discov",
    "cvpr",
    "international semantic web conference",
    "j. web sem",
    "inf. syst",
    "ecir",
    "edbt",
    "inf. retr",
    "web intelligence",
    "appl. intell",
    "applied mathematics and computation",
    "knowl. inf. syst",
    "multimedia tools appl",
    "ieee multimedia",
    "recsys",
    "eswc",
    "cvpr workshops",
    "icpr (3)",
    "icpr",
    "knowledge eng. review",
    "pkdd",
    "acm tist",
    "pakdd",
    "multimedia information retrieval",
    "iswc",
    "siam review",
    "icpr (1)",
    "hypertext",
    "j. intell. inf. syst",
    "ieee/acm trans. comput. biology bioinform",
    "ieee trans. neural netw. learning syst",
    "int j. information management",
    "icpr (4)",
    "ictai",
    "ecml",
    "world wide web",
    "icdt",
    "neural processing letters",
    "j. information science",
    "aaai/iaai",
    "intell. data anal",
    "international journal of uncertainty, fuzziness and knowledge-based systems",
    "dexa workshops",
    "icpr (2)",
    "icdm workshops",
    "ecai",
    "dexa",
    "tweb",
    "tkdd",
    "iswc/aswc",
    "int. j. intell. syst",
    "information technology and management",
    "icde workshops",
    "www (alternate track papers & posters)",
    "neural computing and applications",
    "www (companion volume)",
    "journal of intelligent and fuzzy systems",
    "australian conference on artificial intelligence",
    "foundations and trends in information retrieval",
    "ismis",
    "international semantic web conference (1)",
    "international journal of geographical information science",
    "www (special interest tracks and posters)",
    "ieee communications letters",
    "ecml/pkdd (2)",
    "discovery science",
    "ieee communications magazine",
    "edbt workshops",
    "asonam",
    "ecml/pkdd (1)",
    "icmla",
    "pattern anal. appl",
    "artif. intell. law",
    "ida",
    "dmkd",
    "eswc (1)",
    "dexa workshop",
    "acm multimedia workshops",
    "ai*ia",
    "pakdd (2)",
    "sigcpr",
    "ecml/pkdd (3)",
    "edbt/icdt workshops",
    "foundations and trends in machine learning",
    "kdid",
    "pakdd (1)",
    "acm trans. management inf. syst",
    "pakdd workshops"
]